channels:
  - conda-forge
dependencies:
  - jupyter
  - jupyterlab
  - keras ~= 3.3.0
  - numpy
  - matplotlib
  - pytest
  - pytest-cov
  - pytest-xdist
  - python >= 3.10, < 3.12
  - ruff
  - seaborn
  - scikit-learn
  - scipy ~= 1.13
  - tqdm
  - tox ~= 4.15